### ISSUE TITLE
Inline partials leak fix doesn't work?

### ISSUE THREAD

**Issue by dudabone** [jknack/handlebars.java#655]
Hi @jknack - opening this since I commented in the original issue  #539 and thought you might have missed it. 

Either I didn't get it right or that the fix does not really cover the scenario that I have described. You can see that also in the test that you added the expected result is not the same as I described - the "inherit1" partial is not rendering the "inline partial defined by inherit1, called from base" content, which was defined in the partial block (if needed I can commit a change to the test that better describes the expected result, I believe it will fail though).

I am assuming that this is because the fix requires to call {{>@partial-block}} in order to render the inner content of an inherited partial block, but this does not solve my problem since it requires to go over all templates that are being inherited and add {{>@partial-block}} to them. This is not so applicable since not all inheriting templates actually define a partial block when calling the base template, so you get a "[template] does not provide a @partial-block" exception.

To my understanding the functionality that I am describing (inline partials remaining in the partial block context) is meant to be supported for without the need to call {{>@partial-block}}, as described in the second example of inline partials here ("Each inline partial is available to the current block and all children, including execution of other partials...").

Can you please shed some light on this? Am I missing something? This will be really helpful as my application heavily reuses templates and to workaround this issue I need do define empty inline partials in order to "reset" the ones that were defined by a sibling template.

Thanks!

**Comment by jknack** [comment]
Let's add an example (template+data) of expected vs current output.

**Comment by jknack** [comment]
Fixed. https://github.com/jknack/handlebars.java/releases/tag/v4.1.1

**Comment by dudabone** [comment]
Awesome! 😄 
Will try the new version and update

**Comment by dudabone** [comment]
Sorry @jknack... 🙁 the issue in the scenario I had sent was indeed fixed but in my real app there are some other scenarios where the issue still happens. I will open a new issue with the new example
