### ISSUE TITLE
Reflection illegal access warning

### ISSUE THREAD

**Issue by jernst** [jknack/handlebars.java#863]
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.MemberValueResolver to method java.util.Collections$EmptyMap.isEmpty()
WARNING: Please consider reporting this to the maintainers of com.github.jknack.handlebars.context.MemberValueResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This is Java 11.0.11

**Comment by jknack** [comment]
Fixed here: https://github.com/jknack/handlebars.java/pull/893/commits/11d599f65f2b991e52d94c1b8efba754d0d3d1ea

**Comment by spacether** [comment]
Anyone still getting this?
I am getting it:
```
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.table
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.entrySet
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.size
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.modCount
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.threshold
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.HashMap.loadFactor
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.AbstractMap.keySet
WARNING: Illegal reflective access by com.github.jknack.handlebars.context.FieldValueResolver$FieldMember (file:/Users/justinblack/.m2/repository/com/github/jknack/handlebars/4.2.1/handlebars-4.2.1.jar) to field java.util.AbstractMap.values
```
In my commit here:
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/129/commits/a3bb821be4d9cece18c6ac8cc909b1bf57842fe9#diff-e4f9c78c76ed288a7986147f0905362b6d0ab0542c1495f970fe8207b5fb80c7

**Comment by spacether** [comment]
Hmm upgrading to v4.3.0 eliminated this warning for me.
