### ISSUE TITLE
The nashorn is being used but not included in java 15+

### ISSUE THREAD

**Issue by ali-v-1985** [jknack/handlebars.java#911]
In the `handlebars.java 4.3.0` the problem with java 15+ supposed to be solved but the code below is still trying to get instance of `nashorn` script engine, which is not included in jdk any more.

https://github.com/jknack/handlebars.java/blob/ef79693a7d49ccfe28da7da12355db331a0cb317/handlebars/src/main/java/com/github/jknack/handlebars/helper/DefaultHelperRegistry.java#L302

The code is being referenced via the `registerHelpers` method of `Handlebars` when a js file is being used as the helper source.

Here is the pull request which addressed the issue 
#867 

The following is the stacktrace which resulted by calling `registerHelpers` method.
```
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.engine" is null
  
  at com.github.jknack.handlebars.helper.DefaultHelperRegistry.engine(DefaultHelperRegistry.java:304)
  at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:193)
  at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:173)
  at com.github.jknack.handlebars.Handlebars.registerHelpers(Handlebars.java:750)
```

**Comment by dpozinen** [comment]
@comoroberto where you able to resolve your issue? 

I am using handlebars as part of [git-changelog-lib](https://github.com/tomasbjerre/git-changelog-lib) and have added `nashorn` manually as well. Build is still failing with the mentioned NPE though.

**Comment by comoroberto** [comment]
> @comoroberto where you able to resolve your issue?
> 
> I am using handlebars as part of [git-changelog-lib](https://github.com/tomasbjerre/git-changelog-lib) and have added `nashorn` manually as well. Build is still failing with the mentioned NPE though.

Resolved. I had to clean my local .m2 repository and perform some maven clean on the project.

**Comment by MikalaiHarnouski** [comment]
I am using handlebars as part of [git-changelog-lib](https://github.com/tomasbjerre/git-changelog-lib) with java 11. Build is still failing with the NPE .

[ERROR] GitChangelog
java.lang.NullPointerException
    at com.github.jknack.handlebars.helper.DefaultHelperRegistry.engine (DefaultHelperRegistry.java:304)
    at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers (DefaultHelperRegistry.java:193)
    at com.github.jknack.handlebars.Handlebars.registerHelpers (Handlebars.java:859)

but nashorn  is a part of  java 11

**Comment by jonespm** [comment]
It _looks_ like this was originally fixed for Java 11 on #702 and #731.

However that change was reverted in 865f2d7f3c91a76a41cf855e7fac1e8a112c3056 and 4.3.0, 4.3.1 no longer work on Java 11 giving the original NPE again. Having to stay on 4.2.1 currently.
